project:
  type: website
  output-dir: docs

website:
  title: "jimmie munyi"
  site-url: https://jimmiemunyi.dev/
  description: "thoughts"
  favicon: favicon.png
  google-analytics: G-0HHNW4RVEE
  navbar:
    left:
      - href: about.qmd
        text: about
      - href: notes.qmd
        text: notes
    right:
      - icon: github
        href: https://github.com/jimmiemunyi
      - icon: twitter
        href: https://twitter.com/jimmie_munyi
      - icon: rss
        href: index.xml
  page-footer: 
    left: "Copyright 2022, Jimmie Munyi" 
    right: 
      - icon: github
        href: https://github.com/jimmiemunyi
      - icon: twitter 
        href: https://twitter.com/jimmie_munyi
  open-graph: true
  twitter-card:
    creator: "@jimmie_munyi"
  reader-mode: true
format:
  html:
    theme: 
      light: litera
    css: styles.css



