project:
  type: website
  output-dir: docs

website:
  title: "Jimmie Munyi"
  site-url: https://jimmiemunyi.dev/
  description: "Tech Blog"
  favicon: favicon.png
  google-analytics: G-0HHNW4RVEE
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: thoughts.qmd
        text: Thoughts
      - href: notes.qmd
        text: Notes
      - href: til.qmd
        text: TIL

    right:
      - icon: github
        href: https://github.com/jimmiemunyi
      - icon: twitter
        href: https://twitter.com/jimmie_munyi
      - icon: rss
        href: index.xml
  page-footer: 
    left: "Copyright 2023, Jimmie Munyi" 
    right: 
      - icon: github
        href: https://github.com/jimmiemunyi
      - icon: twitter 
        href: https://twitter.com/jimmie_munyi
  open-graph: true
  twitter-card: true
  reader-mode: true
format:
  html:
    theme: 
      light: litera
    css: styles.css



