project:
  type: website
  output-dir: docs

website:
  title: "Jimmie Munyi"
  fav-icon: favicon.ico
  navbar:
    right:
      - projects.qmd
      - about.qmd
      - icon: github
        href: https://github.com/jimmiemunyi
      - icon: twitter
        href: https://twitter.com/jimmie_munyi
  page-footer: 
    left: "Copyright 2022, Jimmie Munyi" 
    right: 
      - icon: github
        href: https://github.com/jimmiemunyi
      - icon: twitter 
        href: https://twitter.com/jimmie_munyi
  opengraph: true
  twitter-card: true
  reader-mode: true
format:
  html:
    theme: 
      light: litera
      dark: darkly
    css: styles.css



